<a href="https://colab.research.google.com/github/ShumailaAhmed/AI-Workshop/blob/main/LinearModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch


In [ ]:
w = torch.tensor(3.0,requires_grad=True)
b = torch.tensor(1.0,requires_grad=True)


In [ ]:
def forward(x):
  y = w*x+b
  return y

In [ ]:
x= torch.tensor(2)
forward(x)


tensor(7., grad_fn=<AddBackward0>)

In [ ]:
x= torch.tensor([[2],[4],[7]])
forward(x)


tensor([[ 7.],
        [13.],
        [22.]], grad_fn=<AddBackward0>)

In [7]:
from torch.nn import Linear

In [8]:
torch.manual_seed(1)# set seed for reproducibility

In [11]:
model = Linear(in_features=1, out_features=1) #for every prediction we make, for everyoutput there is a single input
print(model.bias, model.weight)
# equation y =  0.5153*x -0.4414 

Parameter containing:
tensor([0.4694], requires_grad=True) Parameter containing:
tensor([[-0.1939]], requires_grad=True)


In [13]:
x = torch.tensor([2.0])
print(model(x))

tensor([0.0816], grad_fn=<AddBackward0>)


In [14]:
x = torch.tensor([[2.0],[3.3],[4.0]])
print(model(x))

tensor([[ 0.0816],
        [-0.1704],
        [-0.3061]], grad_fn=<AddmmBackward>)
